(() => {
  const vscode = acquireVsCodeApi(); const canvas = document.getElementById('screen'); const ctx = canvas.getContext('2d');
  const W = 10, H = 20, shades = ['#b8c99a', '#83956a', '#4e603d', '#1e2b1d']; const shapes = [[[0,0],[1,0],[0,1],[1,1]],[[0,0],[1,0],[2,0],[3,0]],[[0,0],[1,0],[2,0],[1,1]],[[0,0],[0,1],[1,1],[2,1]],[[2,0],[0,1],[1,1],[2,1]],[[1,0],[2,0],[0,1],[1,1]],[[0,0],[1,0],[1,1],[2,1]]];
  let board, piece, next, score, lines, best = 0, runs = 0, enemy = { name: 'BUG', hp: 10, maxHp: 10 }, energy, tick, timer, status = 'MENU', recorded = [], lastRun = null;
  const reset = () => { board = Array.from({length:H}, () => Array(W).fill(0)); next = [0,1,2,3,4]; score = lines = energy = tick = 0; enemy = {name:'BUG',hp:10,maxHp:10}; recorded = []; piece = null; };
  const cells = p => shapes[p.type].map(([x,y]) => { for(let n=0;n<p.rot;n++){[x,y]=[-y,x];} return [p.x+x,p.y+y]; });
  const valid = p => cells(p).every(([x,y]) => x>=0&&x<W&&y>=0&&y<H&&!board[y][x]);
  const spawn = () => { piece={type:next.shift(),rot:0,x:3,y:0}; next.push((next[next.length-1]+3)%7); if(!valid(piece)){status='OVER'; stop(); lastRun=[...recorded]; best=Math.max(best,score); runs++; vscode.postMessage({type:'saveState',score});} };
  const lock = () => { cells(piece).forEach(([x,y])=>board[y][x]=1); let clear=0; board=board.filter(row=>{if(row.every(Boolean)){clear++;return false;}return true;}); while(board.length<H)board.unshift(Array(W).fill(0)); if(clear){lines+=clear;score += [0,100,250,450,700][Math.min(clear,4)] + 50; enemy.hp -= [0,1,3,5,8][Math.min(clear,4)]; if(enemy.hp<=0){score+=500; enemy={name:enemy.name==='BUG'?'REGRESSION':'TIMEOUT',hp:enemy.name==='BUG'?16:24,maxHp:enemy.name==='BUG'?16:24};}} spawn(); };
  const drop = hard => {let d=0; while(valid({...piece,y:piece.y+1})){piece.y++;d++;if(!hard)break;} if(hard){score+=d*2;record('HD');} if(!hard&&!valid({...piece,y:piece.y+1}))lock(); else if(hard)lock();};
  const record = command => { if(status==='PLAYING') recorded.push([tick,command]); };
  const action = command => { if(status!=='PLAYING'&&status!=='REPLAY')return; if(command==='L'&&valid({...piece,x:piece.x-1})){piece.x--;record(command);} if(command==='R'&&valid({...piece,x:piece.x+1})){piece.x++;record(command);} if(command==='CW'&&valid({...piece,rot:(piece.rot+1)%4})){piece.rot=(piece.rot+1)%4;record(command);} if(command==='SD')drop(false); if(command==='HD')drop(true); if(command==='B'&&energy>=3){energy-=3;board.shift();board.push(Array(W).fill(0));record(command);} };
  const start = () => { reset(); status='PLAYING'; spawn(); stop(); timer=setInterval(()=>{tick++;if(tick%18===0)drop(false);draw();},50); draw(); };
  const stop = () => { if(timer){clearInterval(timer);timer=null;} };
  const replay = () => { if(!lastRun)return; start(); lastRun=[...lastRun]; status='REPLAY'; const events=[...lastRun]; stop(); let i=0; timer=setInterval(()=>{tick++;while(i<events.length&&events[i][0]===tick){action(events[i][1]);i++;}if(tick>Math.max(300,events.at(-1)?.[0]||0)){stop();status='VERIFIED';}draw();},50); };
  const draw = () => { ctx.fillStyle=shades[0];ctx.fillRect(0,0,160,144);ctx.fillStyle=shades[3];ctx.font='8px monospace';ctx.fillText('OFFCYCLE',5,9);ctx.fillText(status==='REPLAY'?'REPLAY':status==='MENU'?'READY':status==='OVER'?'RUN OVER':'RUNNING',105,9);ctx.fillText('SCORE '+String(score).padStart(5,'0'),5,140);ctx.fillText(enemy.name,100,21);ctx.fillText('HP '+enemy.hp+'/'+enemy.maxHp,100,29);const ox=5,oy=25,s=6;ctx.fillStyle=shades[1];ctx.fillRect(ox,oy,W*s,H*s);board.forEach((row,y)=>row.forEach((v,x)=>{if(v){ctx.fillStyle=shades[3];ctx.fillRect(ox+x*s,oy+y*s,s-1,s-1);}}));if(piece&&status!=='OVER'&&status!=='MENU'){ctx.fillStyle=shades[2];cells(piece).forEach(([x,y])=>ctx.fillRect(ox+x*s,oy+y*s,s-1,s-1));}ctx.fillStyle=shades[3];ctx.fillText('LINES '+lines,100,42);ctx.fillText('BEST '+best,100,50);ctx.fillText('RUNS '+runs,100,58);if(status==='OVER'){ctx.fillText('SPACE: AGAIN',92,125);}if(status==='VERIFIED'){ctx.fillText('HASH MATCH',92,125);}};
  document.querySelector('[data-action="start"]').onclick=()=>{if(status==='PLAYING'){lastRun=[...recorded];}start();};document.querySelector('[data-action="replay"]').onclick=replay;document.addEventListener('keydown',e=>{if(e.key==='Escape'&&status==='REPLAY'){stop();status='MENU';draw();return;}if(status==='OVER'&&e.code==='Space'){lastRun=[...recorded];start();return;}if(status!=='PLAYING')return;({ArrowLeft:()=>action('L'),a:()=>action('L'),ArrowRight:()=>action('R'),d:()=>action('R'),ArrowDown:()=>action('SD'),x:()=>action('CW'),z:()=>action('CCW'),b:()=>action('B'), ' ':()=>action('HD')})[e.key]?.();});window.addEventListener('message',e=>{if(e.data.type==='state'){best=e.data.state.best;runs=e.data.state.runs;}if(e.data.type==='agent'&&status==='PLAYING'&&(e.data.event==='TEST_PASS'||e.data.event==='BUILD_PASS')){energy=Math.min(9,energy+(e.data.event==='BUILD_PASS'?3:1));recorded.push([tick,e.data.event]);}draw();});vscode.postMessage({type:'getState'});reset();draw();
})();
